### ISSUE TITLE
Publish documentation using GitHub Pages

### ISSUE THREAD

**Issue by hectorespert** [Naguissa/uRTCLib_doc_and_extras#1]
[GitHub Pages](https://pages.github.com/) allow to publish a documentation webpagen using this current repository.

The only chage that this repo requires to publish content is rename `doc` folder to `docs` and enable GitHub pages in repo config: https://help.github.com/es/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

This is an example: http://www.blackleg.es/uRTCLib_doc_and_extras

**Comment by Naguissa** [comment]
Thanks! I knew about github.io, but I was using it for other usecase and didn't know it could be used like that.

I've configured all 'doc_and_extras' repositories and linked original projects.

It's much useful now!

¡Saludos!
